version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '15:10'
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      bun-minor-patch:
        patterns: ['*']
        update-types: [minor, patch]
